# Generated by Django 3.2.7 on 2022-07-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
