# Generated by Django 4.0.4 on 2022-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cards_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to='cards/'),
        ),
    ]
