# Generated by Django 3.2.7 on 2022-08-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_cards_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='card_meaning_ukr',
            field=models.TextField(blank=True),
        ),
    ]
